// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccmoxgvhzsaypgpdzust.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjbW94Z3ZoenNheXBncGR6dXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTA1MzIsImV4cCI6MjA3MzkyNjUzMn0.Gd1YVRKwt2El9iVFUPuGl7j3_IHPZMFKYUfkDQ6qbgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});